title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to the Docyard documentation!

        Have a question instead? Ask in [Discussions Q&A](https://github.com/sanifhimani/docyard/discussions/categories/q-a).

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of your documentation suggestion.
      placeholder: What would you like to see improved or added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Explain why this documentation change would be valuable.
      placeholder: What problem does this solve? Who would benefit?
    validations:
      required: true

  - type: textarea
    id: related-pages
    attributes:
      label: Related pages
      description: Are there existing pages this relates to?
      placeholder: |
        - https://docyard.org/...
        - https://docyard.org/...
    validations:
      required: false

  - type: checkboxes
    id: participation
    attributes:
      label: Participation
      options:
        - label: I'm willing to submit a pull request for this change
